### ISSUE TITLE
Concat v8 breaks apache v5.6.0

### ISSUE THREAD

**Issue by jcwarp** [puppetlabs/puppetlabs-concat#771]
Just FYI, using the newest concat breaks the old apache code:

Failed to generate additional resources using 'eval_generate': undefined method `filter_map' for #<Array:0x0000000003db80c8>
Did you mean? flat_map
Source:/Stage[main]/Apache/Apache::Vhost[default-ssl]/Concat[15-default-ssl.conf]/Concat_file[15-default-ssl.conf]File:/etc/puppetlabs/code/environments/production/modules/concat/manifests/init.ppLine:157
2023-04-1216:26 Z | err |

**Comment by LukasAud** [comment]
Hi @jcwarp, thanks for reporting this issue. Our Puppet 8 support update has bumped the expected minimum ruby version from 2.5 (our previous minimum while Puppet 6 was supported) to 2.7 (the required minimum to run on Puppet 7). This change has translated into a series of Rubocop updates, including the usage of `.filter_map` (introduced in Ruby 2.7) instead of `.map().compact`.

We are currently working on updating all modules to drop support for Puppet 6 and introduce it for Puppet 8, including Apache. Unfortunately, that means this issue doesn't really have a fix. If you want to resume normal operations, you can update to Puppet 7, or pin the concat module to the previous version and wait for Puppet 8 support for Apache to be released as well, then upgrade directly to our latest Puppet agent.

Sorry for the inconvenience.

**Comment by saz** [comment]
@LukasAud So... v8 of this module is dropping support for Puppet 6? Sounds like a change which should have been reflected in the changelog.

**Comment by LukasAud** [comment]
@saz That is actually correct. It seems like a mistake was made during the naming of this (and some other) modules. We will be addressing them asap. For now, #773 has been created to address concat.

**Comment by alexjfisher** [comment]
Fixed in https://github.com/puppetlabs/puppetlabs-concat/pull/776

**Comment by LukasAud** [comment]
Hey @jcwarp, it looks like this issue was addressed. Can you confirm that this issue has been resolved on your end and, if so, close this issue?

**Comment by jcwarp** [comment]
The issue was fixed!
Thanks everyone!
