### ISSUE TITLE
Puppet agent high CPU load with v8

### ISSUE THREAD

**Issue by evgenkisel** [puppetlabs/puppetlabs-concat#778]
## Describe the Bug
I use Foreman with Katello plugin to manage our infrastructure. We sync all modules from the Puppet Forge and use latest versions in our envs. I published a new version of Puppet environment with latest versions of necessary modules and Puppet agents started to get this error and consume CPU:
`Error: /Stage[main]/Aide/Concat[/etc/aide.conf]/Concat_file[/etc/aide.conf]: Failed to generate additional resources using 'eval_generate': undefined method 'filter_map' for #<Array:0x00000000060dc270>
Did you mean?  flat_map`

## Environment
 - Version [8.0.0]
 - Platform [CentOS Linux release 7.9.2009]
 - Puppet Version [6.28.0]
 - Puppet Server[6.17.0]

**Comment by ekohl** [comment]
You're using a module that's incompatible with Puppet 6. It was reverted in https://github.com/puppetlabs/puppetlabs-concat/pull/776 but that's unreleased. Though you should note that it doesn't declare itself compatible with Puppet 6. It is recommended to upgrade since Puppet 6 is EOL. If you can't, you should stick to concat 7.x.

**Comment by evgenkisel** [comment]
> You're using a module that's incompatible with Puppet 6. It was reverted in #776 but that's unreleased. Though you should note that it doesn't declare itself compatible with Puppet 6. It is recommended to upgrade since Puppet 6 is EOL. If you can't, you should stick to concat 7.x.

Thank you!
